### ISSUE TITLE
Choose Batman font

### ISSUE THREAD

**Issue by rafdulaf** [rafdulaf/companion4monolith#100]

**Comment by madcollectordev** [comment]
I like Bahnschrift light semicondensed, but can't make it work with CSS (I just managed Bahnschrift, without 'light semicondensed' which makes it a lot better imho)

**Comment by madcollectordev** [comment]
By the way : here's my default view on firefox PC

The main skill text is bigger than the skill title. The title should be bigger (i.e : "attaque sournoise" should be bigger than "Permet à son possesseur...")
A like the categories and the title the way they are.

![image](https://user-images.githubusercontent.com/34870193/104284295-14836780-54b2-11eb-9cb7-c983df53157a.png)

Also, the W in the slick tabs are weird (see NarroWs Chronicles, or Wayne Manor)

**Comment by rafdulaf** [comment]
I will try this font.
For the text size this is because the skills has not been refactored yet.

**Comment by rafdulaf** [comment]
So this font does not comes from the rulebook ?

**Comment by rafdulaf** [comment]
Looks like it is a commercial font, that is probably why you could not make it work.
Don't think it is too similar to the current Primary font (Rajdhani-Bold_1x)

**Comment by rafdulaf** [comment]
Have a look to this https://fonts.google.com/specimen/Rajdhani#pairings
It proposes other fonts that goes together well

**Comment by madcollectordev** [comment]
I like the Montserrat one

**Comment by rafdulaf** [comment]
Finally staying on a fixed version of existing fonts
