### ISSUE TITLE
Page de configuration des extensions : ordre

### ISSUE THREAD

**Issue by Renand** [rafdulaf/companion4monolith#108]
Bonjour, 
C'est juste une remarque, mais instinctivement, j'aurais imaginé une inversion des colonnes avec la picking zone sur la droite.
J'imagine que c'est lié au fait que je pense que ce contenu est "moins important" que les extensions saison 1 et 2

![image](https://user-images.githubusercontent.com/738859/106013833-21f93e00-60bd-11eb-8088-7398e09d0e69.png)

**Comment by rafdulaf** [comment]
c'est tout à fait juste.
quand Conqueror va arriver cet écran sera à reprendre aussi pour Conan.

là clairement c'est juste pq l'ordre est géré de manière bizarre pour optimiser le rangement :) 

donc je garde ce ticket pour plus tard.
