### ISSUE TITLE
picto centre de zone

### ISSUE THREAD

**Issue by Renand** [rafdulaf/companion4monolith#109]
Je cherche à bien comprendre pourquoi les pictos ne sont pas toujours identiques les un des autres, comme celui-ci par exemple.

![image](https://user-images.githubusercontent.com/738859/106014531-dc894080-60bd-11eb-8e1b-04bc30c68200.png)

Est-ce pour matérialisé les différents niveaux ?
Si c'est le cas, je ne crois pas avoir vu de légende sur ce point.

**Comment by rafdulaf** [comment]
C'est tout à fait ça.
Si tu cliques sur la légende en haut à droite tu obtiens un écran comme ça
![image](https://user-images.githubusercontent.com/1202407/106015230-8cf74480-60be-11eb-9b14-5a59fa5fa47b.png)

et la dernière phrase explique. mais pitet n'est elle pas claire sur le fait qu'il faut compter les cercles. qu'en penses-tu ?

**Comment by Renand** [comment]
j'ajoute que ça semble en décalage d'un niveau. Je m'explique.
Pour moi, 3 lignes vertes c'est niveau 3, alors que sur la map que je regarde ça me dit que pour les 3 lignes, j'ai une chute de niveau 2, je ne sais pas si je suis clair ?

Elle est ou cette légende ? Il faudrait pouvoir y accéder depuis la map, non ?

**Comment by rafdulaf** [comment]
Alors pour la notion de décalage oui je comprends mais pas sûr qu'on puisse y faire quoi que ce soit.
Les cercles ont compte les différences de niveaux qui peuvent engendrer un bonus ; et ça ne correspond pas forcément au texte qui explique les niveaux... déjà parce que 1 cercle c'est le niveau 0...
@madcollectordev ton sentiment ?

**Comment by madcollectordev** [comment]
oui j'ai dû tricher sur certaines cartes dont le niveau commence à 0 et non à 1
J'ai surtout conservé le nombre d'écarts de niveaux

**Comment by Renand** [comment]
C’est le coté mnémotechnique qu’il faut que je chope pour lire ça rapidement.

**Comment by madcollectordev** [comment]
tu as le rappel normalement dans l'onglet des règles par carte
![image](https://user-images.githubusercontent.com/34870193/106026860-9ab2c700-60ca-11eb-8cc8-d7918bf27c90.png)

**Comment by Renand** [comment]
Oui, ce qui est bien dans l’idée des ronds verts c’est que l’info est immédiate en même temps que les lignes de vues.
Mais c’est sur que si doute il y a, les règles aident à le lever.

**Comment by madcollectordev** [comment]
Perso les ronds verts je n'arrive pas à les voir, trop petits.

Mais entre 0 et 3, ou 1 et 4, tu as toujours le même dénivelé ;)

**Comment by Renand** [comment]
Merci

**Comment by rafdulaf** [comment]
Je vais quand même mettre à jour le texte de la légende pour bien indiquer que c'est le nombre de cercles qui indique le niveau d'élévation.

**Comment by madcollectordev** [comment]
Tu me diras si je dois mettre à jour les élévations à 0

**Comment by rafdulaf** [comment]
J'ai pas compris le soucis du coup.
Il y a des cartes où tu démarres pas à 0 ?

**Comment by madcollectordev** [comment]
La banque : 
![image](https://user-images.githubusercontent.com/34870193/106050943-12dbb580-60e8-11eb-9ec1-ffea73c8d4c2.png)

Crime Alley : 
![image](https://user-images.githubusercontent.com/34870193/106050999-22f39500-60e8-11eb-9fe1-0245e6207b8e.png)

**Comment by rafdulaf** [comment]
Ah oui compris. 
Ceux que eux appellent "élévation 0" t'as mis 1 cercle sur Crime Allery.
Et inversement ils appellent ça "élévation 1" dans la banque et il y a 0 cercles.

De mon point de vue extérieur, oui ça pourrait être une bonne idée de faire matcher les 2. On bon recherche/remplacer devrait faire le job ? ça ne concerne que ces deux cartes ?

**Comment by madcollectordev** [comment]
j'avais eu peur que le 0 pose pb en fait, d'où le décalage de 1

en cartes avec un niveau 0 il y a 
- Ace Chemicals
- Crime Alley (x2)
- Joker Funhouse
- Batcave
- Sewers
- GCPD

**Comment by rafdulaf** [comment]
Du coup, tu vas faire le décalage pour cette version ?

**Comment by madcollectordev** [comment]
@rafdulaf  OK sur la version alpha
=> tu redéploies la beta ?

**Comment by rafdulaf** [comment]
ok. je ferme le 0.17 et ouvre le 0.18 (j'ai décalé les tickets ouverts qui étaient encore sur la 0.17)
