### ISSUE TITLE
Conan - FR - Typos

### ISSUE THREAD

**Issue by RoolzTOL** [rafdulaf/companion4monolith#113]
Cartes -> Légende (icône "i")

Les cercles verts **indique** le niveau d'élévation d'une zone.
-> indiquent

**Comment by rafdulaf** [comment]
Dans le cadre de l'autre ticket j'ai reformulé en "Le nombre de cercles verts imbriqués au centre d'une zone indique le niveau d'élévation." du coup c'est bon :D
