### ISSUE TITLE
Batman - FR - Typos

### ISSUE THREAD

**Issue by RoolzTOL** [rafdulaf/companion4monolith#114]
Cartes -> Légende (icone "i")

Les cercles verts **indique** le niveau d'élévation d'une zone.
-> indiquent

**Comment by madcollectordev** [comment]
@rafdulaf c'est dans la partie générique ça non ?

**Comment by rafdulaf** [comment]
oui, c'est un doublon de l'autre du coup vu que @RoolzTOL l'a aussi ouvert sur Conan.
Comme j'ai dis dans l'autre ticket de toute manière j'ai reformulé la phrase en 
"Le nombre de cercles verts imbriqués au centre d'une zone indique le niveau d'élévation."
et du coup plus de faute :D
