### ISSUE TITLE
Batman - Hovertext (EN & FR)

### ISSUE THREAD

**Issue by RoolzTOL** [rafdulaf/companion4monolith#122]
Batman FR :
Cartes -> Regles du plateau -> Icône "Téléchargement" :
Le hovertext est "Télécharger les règles de la carte", devrait être "Télécharger les règles du plateau" (cohérence)

Eventuellement, remplacer partout le terme "Carte" par "Plateau", dans Batman FR et Conan FR.

Batman EN :
Boards -> Board Rules -> Icône "Téléchargement" :
Le hovertext est "Dowlnoad the rules for this map", devrait être "Dowlnoad the board rules" (cohérence)

**Comment by rafdulaf** [comment]
J'ai changé partout Carte en Plateau
