### ISSUE TITLE
Ajouter bouton de raccourci Conan <-> Batman

### ISSUE THREAD

**Issue by RoolzTOL** [rafdulaf/companion4monolith#124]
Ce serait peut-être pas mal d'ajouter une icone/bouton qui renvoie directement d'un Compagnon à l'autre (Batman <-> Conan).
Genre sur la page d'accueil "Plateaux".

**Comment by rafdulaf** [comment]
ou plutot dans le menu ?

revenir à l'accueil avec le choix de l'application plutot non ?
