### ISSUE TITLE
Iphone issue when rotating

### ISSUE THREAD

**Issue by rafdulaf** [rafdulaf/companion4monolith#131]
Loading vertical : ok
Rotation horizontal : ok
Rotaiton vertical : ko => the height of the app is half the phone screen

**Comment by Renand** [comment]
Je te confirmes que :
Ce problème ne se produit que si je met l'app sur l'écran d'accueil.
Cela ne pose pas de problème en usage dans le navigateur.

**Comment by rafdulaf** [comment]
Ok merci... c'est un point important!
Et du coup, pas sûr que j'y puisse grand chose :) j'investiguerai

**Comment by rafdulaf** [comment]
Ok, j'ai une piste en réfléchissant :)
A cause des barres d'adresse des navigateurs qui montent et descendent selon le scroll, j'ai un mécanisme manuel qui s'appuie sur la taille de la fenêtre.
Il semble que Safari ne lance pas l'événement de retaillage de la fenêtre en cas de rotation
https://stackoverflow.com/questions/2740857/ipad-doesnt-trigger-resize-event-going-from-vertical-to-horizontal

Auquel cas, il me suffit de gérer l'évènement de changement d'orientation

**Comment by rafdulaf** [comment]
J'ai tenté une correction (dans la branche skin)
A tester
