### ISSUE TITLE
Conan - Cartes équipement & Sorts / Core box vs. SG (Barb-King)

### ISSUE THREAD

**Issue by RoolzTOL** [rafdulaf/companion4monolith#141]
J'ai refait une passe sur les fichiers imprimeur des deux jeux de cartes Equipement et Sort (suite à relecture de scénars divers):
- cartes Core
- cartes SG (Barbarian + King)
Je pense que la base de données du Companion est OK, mais ça mériterait une vérif supplémentaire.
Ci-dessous ma liste, au cas où.

**Equipement Core :**
armure de cuir x2
cotte de mailles
armure d'écailleS
bouclier
bouclier tribal
écu
kriss
dague x2
dague de parade
poignard yuetshi
lames de lancer
arbalète
javelot x2
arc bossonien
épée
épée de Conan
hache de bataille
lance d'ornement
hallebarde
sceptre de sorcier
orbe explosif x3
grimoire
masse tribale
potion de vie x3
outils
clef
fétiche picte
coffre vide x2 (2 artworks différents)
artefact stygien
couronne de Xuthal x2

**Equipement SG (Barb - King)**
plastron zingaréen
dague sacrificielle
arc zingaréen
sabre de pirate
épée à deux mains
épée turanienne
hache
sceptre stygien
encensoir
coeur d'ahriman
anneau
orbe explosif
bâton de Mitra
bâton de shaman
bâton noir
miroir hyrkanien
masse de Mitra
alcool picte x2
potion de vie
idole Yag-Kosha
trésor sacré x3 (3 artworks différents)
A, B, C, D, E (5 cartes)
onguent
fiole
potion
élixir
"vide" x5
cape

**Sorts Core :** 
tempête d'éclairs
rage de Bori
morsure de Set
baiser de la mort
drain d'énergie
nuée pestilentielle
halo de Mitra
halo de Set
téléportation
étourdissement
possession de Set
contrôle mental
porté par le vent
télékinésie
guérison de Mitra
don de vie

**Sorts SG (Barb - King):**
rage d'Ymir
nuage mortel
téléportation
main de la mort
flétrissement
oeil de faucon
force de Gullah
archer d'Acheron
barrière des vents
regard d'Ishtar
bénédiction d'Ibis
échappatoire
peau de pierre
ralentissement
assèchement de la terre
larmes de Dagon
inversion
rappel
peau d'anguille
blocage magique
course vive
léger comme une plume
attaque de Dagon
caresse de Bel
main de Bel
transfert de vie
retour des braves
réveil de Yajur
malchance
charisme divin
destin changeant
putrescence
réveil de Dagon (vide)
noirceur de Gwahlur (vide)
corps d'Hanuman (vide)
chaleur d'Ishtar (vide)
rage de Jhebbal Sag (vide)
sang de Set (vide)
illusion de Set
change-forme
barrière mystique

**Comment by rafdulaf** [comment]
ah super. merci, je vais enfin tirer ça au clair

**Comment by rafdulaf** [comment]
J'ai vérifié. tout est ok.
