### ISSUE TITLE
Batman : règles par défaut

### ISSUE THREAD

**Issue by madcollectordev** [rafdulaf/companion4monolith#143]
A l'ouverture du compagnon (version hébergée sur TO) pour la première fois, on me propose une configuration par défaut.
J'accepte.
Dans l'onglet règles, on me propose 
- Compétences
- Wayne Manor
Pas de règles de bases, et Wayne Manor est une extension.

**Comment by rafdulaf** [comment]
En effet, dans le fichier Batman/general/default.js j'avais mis n'importe quoi comme valeurs par défaut...
