### ISSUE TITLE
Bandeau d'avertissement

### ISSUE THREAD

**Issue by RoolzTOL** [rafdulaf/companion4monolith#147]
Le bandeau d'avertissement à la 1ere connexion cache les menus.
Plusieurs retours de gens qui n'avaient pas compris qu'il fallair le valider et qu'il y avait des trucs en-dessous...
-soit le redimensionner (beaucoup plus gros au milieu de l'écran) pour obliger les utilisateurs à le valider/acquitter.
-soit le virer

![companion web2021-0912](https://user-images.githubusercontent.com/53515040/132984603-0baab860-cbfc-401c-9ac1-994e5e1871ac.jpg)

**Comment by rafdulaf** [comment]
Ouais, je crois que depuis qu'on a refait les thèmes ; elle n'est plus du tout assez visible. Je vais regarder ça

**Comment by RoolzTOL** [comment]
Le pb c'est qu'on croit que ça fait partie du site, c'est trop propre et discret. 
Il faudrait un gros truc bien dégueulasse qui masque les 3/4 de l'écran, comme sur les sites putaclic.

**Comment by rafdulaf** [comment]
avant il faisait la même taille mais ne faisait pas si discret car il avait une bonne grosse couleur bien visible.
je vais faire des essais

**Comment by rafdulaf** [comment]
sur la table, par exemple, fermer automatiquement la barre si tu cliques ailleurs... je vais méditer sur tout ça :)

**Comment by rafdulaf** [comment]
![image](https://user-images.githubusercontent.com/1202407/144755929-5d1ac405-6c16-4674-b8ee-71e06d4422dd.png)
Voilà, j'ai remis un truc bien visible. 
Je l'ai décalé du haut de la page, comme celui qui clique ailleurs sans le fermer voit les onglets du haut quand même ; jusqu'à ce qu'il soit trop ennuyé par le bandeau et le lise :D
