### ISSUE TITLE
Typos Conan FR

### ISSUE THREAD

**Issue by RoolzTOL** [rafdulaf/companion4monolith#149]
Règles
Compétences
  - Sacr**i**fice

Règles
Tome de Skelos
     _Erreurs de trad dans le fichier d'origine, il y aura probablement un errata_
   - p.12 : A. Masse tribale et **Ecu**
   - p.23 : Cache : Épée akbitanienne, **Bouclier**, Coutelas, Dague, Armure de cuir, **Ecu**, Bouclier à pointes, Lames de lancer, Masse tribale

Encyclopédie
Equipements
   - Armure d'écaille**s**
   - Bouclier à pointe**s** 
   - Document**s** du sorcier 

Plateaux
Les Regles de plateau Conqurant (Citadelle et Temple) ne sont pas à jour, ainsi que le petit schéma qui va avec.
![image](https://user-images.githubusercontent.com/53515040/144754969-152ece0f-45a6-4301-b517-5ee38b52b512.png)

**Comment by rafdulaf** [comment]
Pour la page 23 du tome de Skelos, je ne l'ai pas mise en ligne
Pour les règles du temple et de la citadelle, je n'ai pas de différence : sachant que je retire toutes les règles liées aux lignes de vues qui sont déjà visibles du la carte dynamique
