### ISSUE TITLE
Studio : gérer l'upload d'image

### ISSUE THREAD

**Issue by rafdulaf** [rafdulaf/companion4monolith#59]

**Comment by SmallRealities** [comment]
It might be a better option to host your images on google drive or a similar service where you can get the direct URI of the image.

**Comment by rafdulaf** [comment]
I started implementing it but at my first test, when trying to save an uploaded image, I faced the following error message: Failed to execute 'setItem' on 'Storage': Setting the value of 'Conan_StudioHeroSheets' exceeded the quota.
Indeed, the local data authorized by a browser is quite small...

I could use IndexedDB to store more, but it would be a complex feature, so I'd rather drop the feature.
