### ISSUE TITLE
No map scroll on maps index

### ISSUE THREAD

**Issue by madcollectordev** [rafdulaf/companion4monolith#96]
Testé sur tablette android & Firefox beta
Idem sur PC en réduisant la fenêtre

![image](https://user-images.githubusercontent.com/34870193/104104147-94d57d00-52a6-11eb-8830-873b8b531bd9.png)
Impossible de scroller pour voir les maps suivantes
Idem sur Conan

**Comment by rafdulaf** [comment]
oh la regression ! 👎

**Comment by rafdulaf** [comment]
Quand j'ai travaillé sur les "tokens" j'ai fait un truc entré en conflit avec le reste de l'appli.
Je l'ai retiré, mais je comprends pas pourquoi j'ai pensé en avoir eu besoin... du coup ça a peut-être introduit une regression sur les tokens mais j'ai rien vu :(
