### ISSUE TITLE
Add other rule books

### ISSUE THREAD

**Issue by rafdulaf** [rafdulaf/companion4monolith#98]
Versus , Batmobile and maybe others ? (batcave elevator...)

**Comment by madcollectordev** [comment]
PDFs chargés, plus qu'à les référencer

**Comment by rafdulaf** [comment]
Je te laisse compléter le rules.json
En fait, j'ai pas complété, car j'ai fait un essai avec NarrowChronicles, et je savais pas à quelle extension la rattacher, donc j'ai mis "origins": ["corebox"] pour l'instant, mais à changer du coup

**Comment by madcollectordev** [comment]
Done
